-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 16:25:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema personal_finance_coaching_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema personal_finance_coaching_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `personal_finance_coaching_db` DEFAULT CHARACTER SET utf8 ;
USE `personal_finance_coaching_db` ;


-- Table `personal_finance_coaching_db`.`Coaches`

CREATE TABLE IF NOT EXISTS `personal_finance_coaching_db`.`Coaches` (
  `Coach_id` INT NOT NULL COMMENT '	',
  `First_Name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Specialty` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`Coach_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personal_finance_coaching_db`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_coaching_db`.`Clients` (
  `Client_id` INT NOT NULL,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(20) NULL,
  `Coach_id` INT NOT NULL,
  PRIMARY KEY (`Client_id`),
  INDEX `fk_Clients_Coaches_idx` (`Coach_id` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Coaches`
    FOREIGN KEY (`Coach_id`)
    REFERENCES `personal_finance_coaching_db`.`Coaches` (`Coach_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personal_finance_coaching_db`.`SavingsGoals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_coaching_db`.`SavingsGoals` (
  `Goal_id` INT NOT NULL,
  `Goal_name` VARCHAR(45) NULL,
  `Target_amount` DECIMAL(10,2) NULL,
  `Current_amount` DECIMAL(10,2) NULL,
  `Target_date` DATETIME NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`Goal_id`),
  INDEX `fk_SavingsGoals_Clients1_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_SavingsGoals_Clients1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `personal_finance_coaching_db`.`Clients` (`Client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personal_finance_coaching_db`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_coaching_db`.`Transactions` (
  `Transaction_id` INT NOT NULL,
  `Category` VARCHAR(45) NULL,
  `Amount` DECIMAL(10,2) NULL,
  `Transaction_date` DATETIME NULL,
  `Type` VARCHAR(45) NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`Transaction_id`),
  INDEX `fk_Transactions_Clients1_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions_Clients1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `personal_finance_coaching_db`.`Clients` (`Client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





